name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
    tags:
      - "*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew build
      - name: Build docs
        run: ./gradlew doxygen

      - name: Release latest if push to 1.20
        if: ${{ github.ref_type != 'tag' }}
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.CI_GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Pre Release 1.20"
          files: "build/libs/*.jar"

      - name: Publish to Modrinth and github if tagged
        if: ${{ github.ref_type == 'tag' }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-featured: true
          modrinth-unfeature-mode: subset
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          github-tag: ${{ github.ref_name }}
          github-generate-changelog: true
          github-draft: false
          github-token: ${{ secrets.CI_GITHUB_TOKEN }}

          version: ${{ github.ref_name }}
          changelog-file: CHANGELOG.md

          loaders: fabric
          game-version-filter: none
          java: 17

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail

      - name: Deploy if tagged release 🚀
        if: ${{ github.ref_type == 'tag' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          folder: build/docs/doxygen/html